// The `pdf` package marks `TextStyle`, `Border`, `BorderSide`, and
// `BoxDecoration` as having const constructors, but their initializer
// lists contain enum `!=` / `==` comparisons that the analyzer can't
// const-evaluate (`const_eval_type_bool_num_string`). The
// `prefer_const_constructors` lint still fires on every call site —
// silenced for the file because there is no path to actually make those
// expressions const without forking the package.
// ignore_for_file: prefer_const_constructors

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart' show TimeOfDay;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../models/appointment.dart';
import '../models/journal_entry.dart';
import '../models/medication.dart';
import '../models/patient.dart';

part 'pdf_exporter.g.dart';

/// Half-open `[start, end)` window for the journal PDF export
/// (BUILD_SPEC.md §5.5 doctor-visit packet).
///
/// The journal screen passes the same window the on-screen stream uses
/// (defaults to "last 30 days"); the exporter filters entries to those
/// whose [JournalEntry.createdAt] falls inside the range.
@immutable
class DateRange {
  const DateRange({required this.start, required this.end});

  final DateTime start;
  final DateTime end;

  bool contains(DateTime t) => !t.isBefore(start) && t.isBefore(end);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DateRange && other.start == start && other.end == end);

  @override
  int get hashCode => Object.hash(start, end);
}

/// Generates the two v1 PDF artifacts (BUILD_SPEC.md §5.5 + §5.9).
///
/// * [exportRange] — the multi-page "doctor visit packet" the caregiver
///   shares from the journal screen: cover page, behavior summary table,
///   chronological entry log, footer disclaimer.
/// * [crisisCard] — the single-page hospital handoff sheet from the
///   crisis card screen: every [Patient] field from BUILD_SPEC.md §9.1
///   on one page with the "Updated" timestamp + medical-advice footer.
///
/// Both methods return a [Uint8List] so callers can decide what to do
/// with it (share, save, preview). [sharePdf] is the convenience wrapper
/// the journal + crisis screens use to drop straight into the OS share
/// sheet via `printing`.
///
/// [compress] is plumbed through to [pw.Document] so tests can build the
/// PDF with stream compression disabled and assert that a specific
/// substring made it into the byte buffer. Production callers leave it
/// at the default.
class PdfExporter {
  const PdfExporter({this.compress = true, this.clock = DateTime.now});

  final bool compress;
  final DateTime Function() clock;

  /// Always-visible per-page footer (BUILD_SPEC.md §5.5 + §13.1).
  static const String footerDisclaimer =
      'Generated by Holdclose. Not a substitute for medical advice.';

  /// Generate the doctor-visit packet for [entries] filtered to [range].
  /// [caregiverName] is rendered on the cover (falls back to the
  /// patient's primary caregiver name when omitted).
  ///
  /// BUILD_SPEC.md Phase 12.8 — when [medications] or [appointments]
  /// is provided, the packet appends "Active medications" and
  /// "Upcoming appointments" sections respectively. Both lists are
  /// optional so the journal export path can call this without the
  /// tracker tables loaded (the lean-app mode); the crisis card path
  /// still relies on the [Patient.medications] free-text list per
  /// BUILD_SPEC.md §9.1.
  Future<Uint8List> exportRange({
    required List<JournalEntry> entries,
    required Patient patient,
    required DateRange range,
    String? caregiverName,
    List<MedicationWithSchedules> medications =
        const <MedicationWithSchedules>[],
    List<AppointmentWithProvider> appointments =
        const <AppointmentWithProvider>[],
  }) async {
    final pw.Document doc = pw.Document(compress: compress);
    final List<JournalEntry> windowed = entries
        .where((JournalEntry e) => range.contains(e.createdAt))
        .toList()
      ..sort((JournalEntry a, JournalEntry b) =>
          b.createdAt.compareTo(a.createdAt));
    final String caregiver =
        caregiverName ?? patient.primaryCaregiver.name;
    final DateTime now = clock();
    final List<AppointmentWithProvider> upcoming = appointments
        .where((AppointmentWithProvider a) =>
            a.appointment.status == AppointmentStatus.upcoming &&
            !a.appointment.startsAt.isBefore(now))
        .toList()
      ..sort((AppointmentWithProvider a, AppointmentWithProvider b) =>
          a.appointment.startsAt.compareTo(b.appointment.startsAt));

    doc.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.symmetric(horizontal: 36, vertical: 48),
        footer: _pageFooter,
        build: (pw.Context ctx) => <pw.Widget>[
          _cover(
            patient: patient,
            range: range,
            caregiverName: caregiver,
            entryCount: windowed.length,
          ),
          if (medications.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 24),
            _medicationsHeading(medications.length),
            pw.SizedBox(height: 8),
            _medicationsTable(medications),
          ],
          if (upcoming.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 24),
            _appointmentsHeading(upcoming.length),
            pw.SizedBox(height: 8),
            _appointmentsTable(upcoming),
          ],
          pw.SizedBox(height: 24),
          _entriesHeading(windowed.length),
          pw.SizedBox(height: 8),
          ..._entryRows(windowed),
        ],
      ),
    );

    return doc.save();
  }

  /// Generate the one-page hospital handoff card (BUILD_SPEC.md §5.9 +
  /// §9.1). The page carries every [Patient] field so paramedics can
  /// orient from this sheet alone.
  Future<Uint8List> crisisCard(Patient patient) async {
    final pw.Document doc = pw.Document(compress: compress);
    doc.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.symmetric(horizontal: 36, vertical: 48),
        build: (pw.Context ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: <pw.Widget>[
            _crisisHeader(patient),
            pw.SizedBox(height: 16),
            _crisisDiagnosis(patient),
            pw.SizedBox(height: 14),
            _crisisMedications(patient),
            pw.SizedBox(height: 14),
            _crisisAllergies(patient),
            pw.SizedBox(height: 14),
            _crisisBulletGroup('What calms her:', patient.calms),
            pw.SizedBox(height: 14),
            _crisisBulletGroup('What escalates her:', patient.escalates),
            pw.SizedBox(height: 14),
            _crisisContacts(patient),
            pw.SizedBox(height: 14),
            _crisisDirective(patient),
            pw.Spacer(),
            _crisisFooter(),
          ],
        ),
      ),
    );
    return doc.save();
  }

  /// A concise, shareable **care summary** for provider coordination —
  /// conditions, allergies, active medications, and upcoming appointments on
  /// one packet (no behavior journal). Closes the "coordinating between
  /// doctors" gap: the caregiver hands the same current picture to every
  /// clinician. Reuses the crisis + packet render helpers.
  Future<Uint8List> careSummary({
    required Patient patient,
    List<String> conditions = const <String>[],
    List<String> allergies = const <String>[],
    List<MedicationWithSchedules> medications =
        const <MedicationWithSchedules>[],
    List<AppointmentWithProvider> appointments =
        const <AppointmentWithProvider>[],
    String? caregiverName,
  }) async {
    final pw.Document doc = pw.Document(compress: compress);
    final DateTime now = clock();
    final List<AppointmentWithProvider> upcoming = appointments
        .where((AppointmentWithProvider a) =>
            a.appointment.status == AppointmentStatus.upcoming &&
            !a.appointment.startsAt.isBefore(now))
        .toList()
      ..sort((AppointmentWithProvider a, AppointmentWithProvider b) =>
          a.appointment.startsAt.compareTo(b.appointment.startsAt));

    doc.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.symmetric(horizontal: 36, vertical: 48),
        footer: _pageFooter,
        build: (pw.Context ctx) => <pw.Widget>[
          pw.Text('Holdclose',
              style: pw.TextStyle(
                  color: _navy, fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text('Care summary',
              style: pw.TextStyle(
                  color: _navy, fontSize: 28, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 18),
          _coverRow('Loved one', patient.name),
          _coverAgeRow(patient),
          _coverRow('Date', _formatDate(now)),
          if ((caregiverName ?? '').trim().isNotEmpty)
            _coverRow('Caregiver', caregiverName!.trim()),
          if (conditions.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 20),
            _crisisBulletGroup('Conditions', conditions),
          ],
          if (allergies.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 14),
            _crisisBulletGroup('Allergies', allergies),
          ],
          if (medications.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 24),
            _medicationsHeading(medications.length),
            pw.SizedBox(height: 8),
            _medicationsTable(medications),
          ],
          if (upcoming.isNotEmpty) ...<pw.Widget>[
            pw.SizedBox(height: 24),
            _appointmentsHeading(upcoming.length),
            pw.SizedBox(height: 8),
            _appointmentsTable(upcoming),
          ],
        ],
      ),
    );
    return doc.save();
  }

  /// Hand [bytes] to the OS share sheet via `printing`. Thin wrapper so
  /// the journal + crisis screens depend on a single seam rather than
  /// importing `printing` directly.
  Future<bool> sharePdf(Uint8List bytes, {String filename = 'holdclose.pdf'}) {
    return Printing.sharePdf(bytes: bytes, filename: filename);
  }

  // ──────────────────── journal packet ────────────────────

  pw.Widget _cover({
    required Patient patient,
    required DateRange range,
    required String caregiverName,
    required int entryCount,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Text(
          'Holdclose',
          style: pw.TextStyle(
            color: _navy,
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'Doctor visit packet',
          style: pw.TextStyle(
            color: _navy,
            fontSize: 28,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 18),
        _coverRow('Loved one', patient.name),
        _coverAgeRow(patient),
        _coverRow('Date range', _formatRange(range)),
        _coverRow('Caregiver', caregiverName),
        _coverRow('Entries in this packet', entryCount.toString()),
      ],
    );
  }

  /// Cover-block identity row: DOB (what EMS/clinicians expect) plus the
  /// derived age when a date of birth is on file, the stored age otherwise.
  pw.Widget _coverAgeRow(Patient patient) {
    final DateTime? dob = patient.dateOfBirth;
    if (dob == null) return _coverRow('Age', patient.age.toString());
    return _coverRow(
      'Date of birth',
      '${_formatDate(dob)} · ${patient.ageOn(clock())}',
    );
  }

  pw.Widget _coverRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.SizedBox(
            width: 150,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                color: _navy,
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value,
              style: pw.TextStyle(color: _bodyText, fontSize: 12),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _summaryCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          color: bold ? _navy : _bodyText,
          fontSize: 11,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  pw.Widget _entriesHeading(int count) {
    return pw.Text(
      'Entries ($count)',
      style: pw.TextStyle(
        color: _navy,
        fontSize: 16,
        fontWeight: pw.FontWeight.bold,
      ),
    );
  }

  // ──────────────────── medications (Phase 12.8) ────────────────────

  pw.Widget _medicationsHeading(int count) {
    return pw.Text(
      'Active medications ($count)',
      style: pw.TextStyle(
        color: _navy,
        fontSize: 16,
        fontWeight: pw.FontWeight.bold,
      ),
    );
  }

  pw.Widget _medicationsTable(List<MedicationWithSchedules> meds) {
    return pw.Table(
      border: pw.TableBorder.all(color: _rule, width: 0.5),
      columnWidths: const <int, pw.TableColumnWidth>{
        0: pw.FlexColumnWidth(3),
        1: pw.FlexColumnWidth(2),
        2: pw.FlexColumnWidth(4),
        3: pw.FlexColumnWidth(2),
      },
      children: <pw.TableRow>[
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _surfaceWarm),
          children: <pw.Widget>[
            _summaryCell('Medication', bold: true),
            _summaryCell('Dosage', bold: true),
            _summaryCell('Schedule', bold: true),
            _summaryCell('Route', bold: true),
          ],
        ),
        for (final MedicationWithSchedules row in meds)
          pw.TableRow(
            children: <pw.Widget>[
              _summaryCell(row.medication.name),
              _summaryCell(row.medication.dosage),
              _summaryCell(_summariseSchedules(row.windows)),
              _summaryCell(_routeLabel(row.medication.route)),
            ],
          ),
      ],
    );
  }

  // ──────────────────── appointments (Phase 12.8) ────────────────────

  pw.Widget _appointmentsHeading(int count) {
    return pw.Text(
      'Upcoming appointments ($count)',
      style: pw.TextStyle(
        color: _navy,
        fontSize: 16,
        fontWeight: pw.FontWeight.bold,
      ),
    );
  }

  pw.Widget _appointmentsTable(List<AppointmentWithProvider> appts) {
    return pw.Table(
      border: pw.TableBorder.all(color: _rule, width: 0.5),
      columnWidths: const <int, pw.TableColumnWidth>{
        0: pw.FlexColumnWidth(3),
        1: pw.FlexColumnWidth(3),
        2: pw.FlexColumnWidth(3),
        3: pw.FlexColumnWidth(2),
      },
      children: <pw.TableRow>[
        pw.TableRow(
          decoration: pw.BoxDecoration(color: _surfaceWarm),
          children: <pw.Widget>[
            _summaryCell('When', bold: true),
            _summaryCell('Provider', bold: true),
            _summaryCell('Location', bold: true),
            _summaryCell('Duration', bold: true),
          ],
        ),
        for (final AppointmentWithProvider row in appts)
          pw.TableRow(
            children: <pw.Widget>[
              _summaryCell(_formatDateTime(row.appointment.startsAt)),
              _summaryCell(_providerLine(row.provider)),
              _summaryCell(row.appointment.location.isEmpty
                  ? '(not set)'
                  : row.appointment.location),
              _summaryCell('${row.appointment.durationMinutes} min'),
            ],
          ),
      ],
    );
  }

  List<pw.Widget> _entryRows(List<JournalEntry> entries) {
    if (entries.isEmpty) {
      return <pw.Widget>[
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 6),
          child: pw.Text(
            'No entries to show for this date range.',
            style: pw.TextStyle(color: _bodyText, fontSize: 11),
          ),
        ),
      ];
    }
    return <pw.Widget>[
      for (final JournalEntry e in entries) _entryBlock(e),
    ];
  }

  pw.Widget _entryBlock(JournalEntry entry) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _surfaceWarm,
        border: pw.Border.all(color: _rule, width: 0.5),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.Text(
            _formatDateTime(entry.occurredAt ?? entry.createdAt),
            style: pw.TextStyle(
              color: _navy,
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          if (_clean(entry.situationText) case final String situation) ...<pw.Widget>[
            pw.SizedBox(height: 4),
            pw.Text(
              'What happened: $situation',
              style: pw.TextStyle(color: _bodyText, fontSize: 11),
            ),
          ],
          if (_clean(entry.attemptsText) case final String attempts) ...<pw.Widget>[
            pw.SizedBox(height: 4),
            pw.Text(
              'What you tried: $attempts',
              style: pw.TextStyle(color: _bodyText, fontSize: 11),
            ),
          ],
          if (_clean(entry.notes) case final String notes) ...<pw.Widget>[
            pw.SizedBox(height: 4),
            pw.Text(
              'Notes: $notes',
              style: pw.TextStyle(color: _bodyText, fontSize: 11),
            ),
          ],
        ],
      ),
    );
  }

  /// Trimmed text, or null when the field is null/blank — lets the entry
  /// block use a `case final String` pattern to drop empty sections.
  static String? _clean(String? raw) {
    final String? trimmed = raw?.trim();
    if (trimmed == null || trimmed.isEmpty) return null;
    return trimmed;
  }

  pw.Widget _pageFooter(pw.Context ctx) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: _rule, width: 0.5),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: <pw.Widget>[
          pw.Text(
            footerDisclaimer,
            style: pw.TextStyle(color: _bodyText, fontSize: 9),
          ),
          pw.Text(
            'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
            style: pw.TextStyle(color: _bodyText, fontSize: 9),
          ),
        ],
      ),
    );
  }

  // ──────────────────── crisis card ────────────────────

  pw.Widget _crisisHeader(Patient patient) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Text(
          'Hospital handoff card',
          style: pw.TextStyle(
            color: _navy,
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          patient.name,
          style: pw.TextStyle(
            color: _navy,
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.Text(
          // DOB, not age, is what an ER handoff needs — fall back to the
          // stored age only for profiles without a date of birth on file.
          patient.dateOfBirth == null
              ? 'Age ${patient.age}'
              : 'DOB ${_formatDate(patient.dateOfBirth!)} · '
                  '${patient.ageOn(clock())}',
          style: pw.TextStyle(color: _bodyText, fontSize: 12),
        ),
      ],
    );
  }

  pw.Widget _crisisDiagnosis(Patient patient) {
    return _crisisSection(
      heading: 'Diagnosis',
      body: <pw.Widget>[
        pw.Text(
          patient.diagnosis,
          style: pw.TextStyle(color: _bodyText, fontSize: 12),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'Diagnosed ${_formatDate(patient.diagnosedAt)}',
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
      ],
    );
  }

  pw.Widget _crisisMedications(Patient patient) {
    return _crisisSection(
      heading: 'Medications',
      body: <pw.Widget>[
        if (patient.medications.isEmpty)
          pw.Text(
            'None on file.',
            style: pw.TextStyle(color: _bodyText, fontSize: 11),
          )
        else
          for (final CrisisMedication m in patient.medications)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 2),
              child: pw.Text(
                '${m.name} ${m.dose} - ${m.schedule}',
                style: pw.TextStyle(color: _bodyText, fontSize: 11),
              ),
            ),
      ],
    );
  }

  pw.Widget _crisisAllergies(Patient patient) {
    return _crisisSection(
      heading: 'Allergies',
      body: <pw.Widget>[
        pw.Text(
          patient.allergies.isEmpty
              ? 'None on file.'
              : patient.allergies.join(', '),
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
      ],
    );
  }

  pw.Widget _crisisBulletGroup(String heading, List<String> items) {
    return _crisisSection(
      heading: heading,
      body: <pw.Widget>[
        if (items.isEmpty)
          pw.Text(
            '(none)',
            style: pw.TextStyle(color: _bodyText, fontSize: 11),
          )
        else
          for (final String item in items)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 2),
              child: pw.Text(
                '- $item',
                style: pw.TextStyle(color: _bodyText, fontSize: 11),
              ),
            ),
      ],
    );
  }

  pw.Widget _crisisContacts(Patient patient) {
    return _crisisSection(
      heading: 'Contacts',
      body: <pw.Widget>[
        pw.Text(
          'Primary caregiver: ${patient.primaryCaregiver.name} '
          '- ${patient.primaryCaregiver.phone}',
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'Healthcare POA: ${patient.healthcarePOA.name} '
          '- ${patient.healthcarePOA.phone}',
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
      ],
    );
  }

  pw.Widget _crisisDirective(Patient patient) {
    final String dnr = patient.advanceDirective.dnr ? 'Yes' : 'No';
    return _crisisSection(
      heading: 'Advance directive',
      body: <pw.Widget>[
        pw.Text(
          'On file at: ${patient.advanceDirective.onFileAt}',
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'DNR: $dnr',
          style: pw.TextStyle(color: _bodyText, fontSize: 11),
        ),
      ],
    );
  }

  pw.Widget _crisisSection({
    required String heading,
    required List<pw.Widget> body,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Text(
          heading,
          style: pw.TextStyle(
            color: _navy,
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 4),
        ...body,
      ],
    );
  }

  pw.Widget _crisisFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Divider(color: _rule, height: 8),
        pw.SizedBox(height: 4),
        pw.Text(
          'Updated ${_formatDate(clock())}',
          style: pw.TextStyle(color: _bodyText, fontSize: 10),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          footerDisclaimer,
          style: pw.TextStyle(color: _bodyText, fontSize: 9),
        ),
      ],
    );
  }

  // ──────────────────── helpers ────────────────────
}

/// One row in the "Active medications" PDF section (BUILD_SPEC.md Phase
/// 12.8, v14 windows pivot).
///
/// Pairs the [Medication] with the (window, entry) pairs it
/// participates in so the exporter can render a human-readable
/// summary ("Morning · Bedtime") without re-querying drift mid-render.
@immutable
class MedicationWithSchedules {
  const MedicationWithSchedules({
    required this.medication,
    required this.windows,
  });

  final Medication medication;

  /// One entry per window this medication appears in. The exporter
  /// joins the window labels for the summary cell.
  final List<({DoseWindow window, MedicationWindowEntry entry})> windows;
}

/// One row in the "Upcoming appointments" PDF section (BUILD_SPEC.md
/// Phase 12.8).
///
/// Pairs the [Appointment] with its [Provider] (when known) so the
/// exporter can render "Dr. Patel, Neurologist — Jun 4 2026, 10:00 AM"
/// without joining tables at render time. The provider is nullable for
/// the rare case where a provider was deleted but its appointment row
/// survived (DB FK should cascade, but defending here keeps the render
/// path total).
@immutable
class AppointmentWithProvider {
  const AppointmentWithProvider({
    required this.appointment,
    required this.provider,
  });

  final Appointment appointment;
  final Provider? provider;
}

// Brand tokens duplicated as `PdfColor` values rather than imported from
// `lib/theme.dart` — the Flutter `Color` type isn't usable inside the
// `pdf` package's `widgets.dart` painter. The hex values match
// BUILD_SPEC.md §3.1 verbatim.
final PdfColor _navy = PdfColor.fromInt(0xFF1F2A44);
final PdfColor _bodyText = PdfColor.fromInt(0xFF33373D);
final PdfColor _surfaceWarm = PdfColor.fromInt(0xFFF8F6F3);
final PdfColor _rule = PdfColor.fromInt(0xFFCCCCCC);

String _formatRange(DateRange range) {
  return '${_formatDate(range.start)} - ${_formatDate(range.end)}';
}

String _formatDate(DateTime t) {
  final String month = _months[t.month - 1];
  return '$month ${t.day}, ${t.year}';
}

String _formatDateTime(DateTime t) {
  final int rawHour = t.hour % 12;
  final int hour = rawHour == 0 ? 12 : rawHour;
  final String minute = t.minute.toString().padLeft(2, '0');
  final String suffix = t.hour < 12 ? 'AM' : 'PM';
  return '${_formatDate(t)}  $hour:$minute $suffix';
}

const List<String> _months = <String>[
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
];

/// Render "Morning · Bedtime · Mon Wed Fri Noon" for the PDF
/// medications table (v14 windows pivot).
///
/// Top-level so the test suite can exercise it directly without
/// instantiating the exporter. Joins each window's label with the
/// entry's weekday qualifier when it gates on specific days.
String _summariseSchedules(
    List<({DoseWindow window, MedicationWindowEntry entry})> pairs) {
  if (pairs.isEmpty) return 'As needed';
  return pairs.map(_summariseOne).join(' · ');
}

String _summariseOne(({DoseWindow window, MedicationWindowEntry entry}) p) {
  final DoseWindow w = p.window;
  final MedicationWindowEntry e = p.entry;
  final String anchorPart = w.anchorTime == null
      ? w.label
      : '${w.label} (${_renderTime(w.anchorTime!)})';
  if (e.daysOfWeek.isEmpty) return anchorPart;
  final List<int> days = e.daysOfWeek.toList()..sort();
  const List<String> weekdayNames = <String>[
    'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun',
  ];
  final String dayLabel = days
      .map((int d) {
        final int idx = (d - 1) < 0 ? 0 : (d - 1 > 6 ? 6 : d - 1);
        return weekdayNames[idx];
      })
      .join('/');
  return '$dayLabel $anchorPart';
}

String _renderTime(TimeOfDay t) {
  final int rawHour = t.hour % 12;
  final int hour = rawHour == 0 ? 12 : rawHour;
  final String minute = t.minute.toString().padLeft(2, '0');
  final String suffix = t.hour < 12 ? 'AM' : 'PM';
  return '$hour:$minute $suffix';
}

String _routeLabel(MedicationRoute route) {
  switch (route) {
    case MedicationRoute.oral:
      return 'Oral';
    case MedicationRoute.topical:
      return 'Topical';
    case MedicationRoute.injection:
      return 'Injection';
    case MedicationRoute.other:
      return 'Other';
  }
}

String _providerLine(Provider? p) {
  if (p == null) return 'Provider on file';
  switch (p.role) {
    case ProviderRole.doctor:
      return '${p.name} (Doctor)';
    case ProviderRole.neurologist:
      return '${p.name} (Neurologist)';
    case ProviderRole.socialWorker:
      return '${p.name} (Social worker)';
    case ProviderRole.other:
      return p.name;
  }
}

/// Riverpod-wired singleton (BUILD_SPEC.md §15). The journal + crisis
/// screens read `ref.watch(pdfExporterProvider)` and call into a single
/// shared instance — the exporter is stateless so the keep-alive is just
/// to avoid the per-watch construction.
@Riverpod(keepAlive: true)
PdfExporter pdfExporter(Ref ref) => const PdfExporter();
