import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'medication.freezed.dart';
part 'medication.g.dart';

/// Route of administration for a [Medication] (TASKS.md Phase 12.1).
///
/// Free-text routes the caregiver may need (e.g. "subcutaneous",
/// "patch") collapse onto [other] in v1 — the add-med form (Phase 12.3)
/// pairs the dropdown with a free-text "notes" field on the parent
/// [Medication] so an unusual route can still be captured.
enum MedicationRoute {
  oral,
  topical,
  injection,
  other,
}

/// How often a [DoseSchedule] fires (TASKS.md Phase 12.1).
///
/// [daily] / [twiceDaily] use [DoseSchedule.timesOfDay] for the
/// per-day clock times; [weekly] additionally consults
/// [DoseSchedule.daysOfWeek] to pick which weekdays the doses land on;
/// [asNeeded] ignores both — the caregiver logs each dose ad-hoc and
/// no scheduled rows are generated by `MedicationRepository
/// .upcomingDoses(...)` (Phase 12.2).
enum FrequencyKind {
  daily,
  twiceDaily,
  weekly,
  asNeeded,
}

/// Status of a logged dose (TASKS.md Phase 12.1).
///
/// [taken] — caregiver checked the dose off on time.
/// [missed] — the dose's scheduled window passed without a check-off.
/// [skipped] — caregiver explicitly chose not to give the dose
///   (e.g. patient asleep, vomiting). Distinct from [missed] so the
///   adherence-rate helper (Phase 12.2) can separate "we missed it"
///   from "we deliberately held it".
/// [late] — caregiver checked the dose off after the scheduled window
///   closed. Surfaced with a small badge in the dose-log UI (Phase
///   12.4).
enum DoseStatus {
  taken,
  missed,
  skipped,
  late,
}

/// JSON serializer for Flutter's [TimeOfDay] (TASKS.md Phase 12.1).
///
/// Serializes to a zero-padded 24-hour `HH:mm` string so the rendered
/// blob stays human-readable in sqlite + survives a parse from outside
/// Dart (the doctor-visit PDF export in Phase 12.8 reads schedules
/// straight from the JSON).
class TimeOfDayJsonConverter implements JsonConverter<TimeOfDay, String> {
  const TimeOfDayJsonConverter();

  @override
  TimeOfDay fromJson(String json) {
    final List<String> parts = json.split(':');
    return TimeOfDay(
      hour: int.parse(parts[0]),
      minute: int.parse(parts[1]),
    );
  }

  @override
  String toJson(TimeOfDay value) => '${value.hour.toString().padLeft(2, '0')}:'
      '${value.minute.toString().padLeft(2, '0')}';
}

/// One tracked medication (TASKS.md Phase 12.1).
///
/// The structured counterpart to [CrisisMedication] (the free-text
/// med entry on the crisis card) — this one carries the id every
/// [DoseSchedule] and [DoseLog] FKs onto. Deleting a [Medication]
/// cascades through both child tables (drift FK action wired in
/// `lib/db/database.dart`).
@freezed
abstract class Medication with _$Medication {
  const factory Medication({
    required String id,
    required String name,

    /// Free-text dosage as the caregiver wrote it on the bottle —
    /// "10 mg", "1 tablet", "5 mL". Stored verbatim so transcription
    /// errors trace back to the source.
    required String dosage,
    required MedicationRoute route,

    /// Prescribing clinician (free text). Optional — over-the-counter
    /// entries leave it empty.
    String? prescriber,

    /// Free-text notes the caregiver wants to keep visible on the
    /// med card (e.g. "take with food", "watch for drowsiness").
    String? notes,

    /// Soft-delete tombstone (TASKS.md Phase 15.6). Null for a live
    /// medication; set to the deletion instant when the caregiver removes
    /// it from the list. [MedicationRepository.listMedications] excludes
    /// tombstoned rows so a delete disappears from every derived view
    /// (the dose-log, the home "today" card, adherence) while the row —
    /// and its dose history — stays on disk for an undo / audit trail.
    DateTime? deletedAt,
  }) = _Medication;

  factory Medication.fromJson(Map<String, dynamic> json) =>
      _$MedicationFromJson(json);
}

/// One dosing schedule for a [Medication] (TASKS.md Phase 12.1).
///
/// A medication can carry multiple schedules — e.g. "Donepezil 10 mg
/// every morning" + "Donepezil 5 mg added at noon for the next two
/// weeks" — by inserting two [DoseSchedule] rows that FK onto the same
/// medication id. The repository (Phase 12.2) expands each schedule
/// into concrete `DateTime`s for the upcoming-doses view.
///
/// [timesOfDay] applies to every frequency except [FrequencyKind
/// .asNeeded] (which carries an empty list); [daysOfWeek] only applies
/// to [FrequencyKind.weekly] (and uses the `DateTime.weekday`
/// convention: Monday = 1, Sunday = 7).
@freezed
abstract class DoseSchedule with _$DoseSchedule {
  const factory DoseSchedule({
    required String id,
    required String medicationId,
    required FrequencyKind frequencyKind,
    @TimeOfDayJsonConverter() required List<TimeOfDay> timesOfDay,
    required Set<int> daysOfWeek,
    required DateTime startsOn,
    DateTime? endsOn,
  }) = _DoseSchedule;

  factory DoseSchedule.fromJson(Map<String, dynamic> json) =>
      _$DoseScheduleFromJson(json);
}

/// One logged dose event (TASKS.md Phase 12.1).
///
/// Two-state lifecycle: the repository (Phase 12.2) materializes a
/// [DoseLog] row when a scheduled dose first crosses "now" with
/// [takenAt] null and [status] set to [DoseStatus.missed] (or stays
/// upcoming until the caregiver acts). The dose-log UI (Phase 12.4)
/// flips [status] to [DoseStatus.taken] / [DoseStatus.skipped] /
/// [DoseStatus.late] and stamps [takenAt] when the caregiver acts.
///
/// FK on [medicationId] cascades on delete — wiping a medication wipes
/// its history alongside its schedules.
@freezed
abstract class DoseLog with _$DoseLog {
  const factory DoseLog({
    required String id,
    required String medicationId,
    required DateTime scheduledFor,
    DateTime? takenAt,
    required DoseStatus status,
    String? notes,
  }) = _DoseLog;

  factory DoseLog.fromJson(Map<String, dynamic> json) =>
      _$DoseLogFromJson(json);
}
