import { Hono } from 'hono';

import type { Bindings, Variables } from '../index';

// NOTE: this text is real, shippable policy copy, but it has not yet had
// attorney review — schedule one before store submission. Keep updates to
// the "Last updated" date in LAST_UPDATED so both pages stay in sync.
const LAST_UPDATED = 'July 8, 2026';

/// Shared shell for the two legal pages. Mirrors the /join landing page's
/// look (warm-white background, navy text, system font stack) so the
/// pages read as the same product surface a store reviewer lands on from
/// the sign-in screen's Terms / Privacy links.
function legalPage(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
body{margin:0;background:#f8f6f3;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1f2a44;}
main{max-width:680px;margin:0 auto;padding:40px 24px 64px;}
h1{font-size:28px;line-height:1.3;margin:0 0 4px;}
h2{font-size:19px;line-height:1.35;margin:32px 0 8px;}
p,li{font-size:16px;line-height:1.55;color:#3a4a63;}
p{margin:0 0 14px;}
ul{margin:0 0 14px;padding-left:22px;}
.meta{font-size:14px;color:#7a869a;margin:0 0 28px;}
a{color:#1f2a44;}
</style>
</head>
<body>
<main>
${body}
</main>
</body>
</html>`;
}

const TERMS_HTML = legalPage(
  'Holdclose Terms of Service',
  `<h1>Holdclose Terms of Service</h1>
<p class="meta">Last updated: ${LAST_UPDATED}</p>
<p>Holdclose is operated by Juno Code Studio (JCSV One LLC), a South Carolina limited liability company ("we", "us"). By creating an account or using the Holdclose app, you agree to these Terms of Service. If you do not agree, do not use the app.</p>

<h2>1. What Holdclose is</h2>
<p>Holdclose helps family caregivers organize care for someone they love: medications and dose schedules, appointments, a shared care circle, a health log, a journal, and an AI-powered coach that draws on the care information you record. You are licensed to use the app for personal, non-commercial purposes only.</p>

<h2>2. Not a medical device, not medical advice</h2>
<p>Holdclose is not a medical device and does not provide medical advice, diagnosis, or treatment. The app will not diagnose any condition, recommend medication doses, or make prognosis claims. Nothing in the app — including the AI coach — is a substitute for the judgment of a qualified clinician. Always consult your loved one's doctor, pharmacist, or other qualified health provider with any questions about a medical condition or medication, and never disregard or delay seeking professional advice because of something you read in the app. If you believe there is a medical emergency, call your local emergency number immediately.</p>

<h2>3. AI-generated content</h2>
<p>Parts of Holdclose — the coach chat, document scanning, visit-preparation questions, and letter drafts — are generated by artificial intelligence. AI-generated content can be incomplete, out of date, or simply wrong. It is offered as support for your own thinking, not as a source of truth. All decisions about your loved one's care remain with you and their clinicians, and you are responsible for reviewing anything the app drafts or extracts before relying on it.</p>

<h2>4. Your account and your content</h2>
<p>You are responsible for the accuracy of the information you enter, for keeping your sign-in credentials secure, and for having the right to share any information you add about another person (such as the loved one you care for or members of your care circle). You retain ownership of the content you create in the app.</p>

<h2>5. Acceptable use</h2>
<p>You agree not to misuse the service — including attempting to access other users' data, probing or disrupting our systems, scraping the service, reselling access, or using the app to harass others or to violate any law.</p>

<h2>6. Termination</h2>
<p>You may stop using Holdclose and request deletion of your account at any time by emailing <a href="mailto:support@holdclose.care">support@holdclose.care</a>. We may suspend or terminate accounts that violate these terms, abuse the service, or create risk for other users, and we may discontinue the service or features of it with reasonable notice where practicable.</p>

<h2>7. Disclaimers and limitation of liability</h2>
<p>The service is provided "as is" and "as available", without warranties of any kind, express or implied, including fitness for a particular purpose and non-infringement. To the maximum extent permitted by law, JCSV One LLC and its members, officers, and contractors will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of data, arising out of or relating to your use of the service; and our total aggregate liability for any claim will not exceed the greater of fifty US dollars ($50) or the amount you paid us for the service in the twelve months before the claim arose. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you.</p>

<h2>8. Governing law</h2>
<p>These terms are governed by the laws of the State of South Carolina, USA, without regard to its conflict-of-laws rules, and any dispute will be resolved in the state or federal courts located in South Carolina.</p>

<h2>9. Changes to these terms</h2>
<p>We may update these terms as the product evolves. If a change is material, we will give notice in the app or by email before it takes effect. Continuing to use Holdclose after a change takes effect means you accept the updated terms.</p>

<h2>10. Contact</h2>
<p>Juno Code Studio (JCSV One LLC) &middot; <a href="mailto:support@holdclose.care">support@holdclose.care</a></p>`,
);

const PRIVACY_HTML = legalPage(
  'Holdclose Privacy Policy',
  `<h1>Holdclose Privacy Policy</h1>
<p class="meta">Last updated: ${LAST_UPDATED}</p>
<p>This policy describes what information Holdclose — operated by Juno Code Studio (JCSV One LLC) — collects, how it is used, and the choices you have. The short version: your care data lives on your device by default, we only move it to our servers to provide features you turn on, we do not sell personal data, and there are no ads.</p>

<h2>1. Care data stays on your device by default</h2>
<p>The information you record about your loved one — medications, dose logs, appointments, health log entries, journal entries, and the emergency card — is stored in a local database on your phone. If you never sign in or join a care circle, that data does not leave your device except as described below for AI features you actively use.</p>

<h2>2. Account information</h2>
<p>When you sign in with Google, we store the identity Google asserts for you — your Google account identifier ("sub"), email address, and display name — so we can recognize your account across devices and sign-ins. We do not receive or store your Google password.</p>

<h2>3. Care Circle sync</h2>
<p>If you create or join a Care Circle, the care data you choose to share (such as medications, appointments, tasks, and shifts) is synced through and stored on our backend so the members of your circle can see and update it. Circle invitations are single-use and expire within two days, and joining always requires your explicit in-app confirmation.</p>

<h2>4. AI features</h2>
<p>Some features send data to our service for processing so they can work: messages you send to the coach chat (along with the care context needed to answer), documents you scan (prescriptions, appointment cards, insurance cards), and requests like visit-preparation questions or appeal-letter drafts. This processing exists to provide the feature you invoked — not to build advertising profiles.</p>

<h2>5. Feedback reports</h2>
<p>If you submit an in-app feedback report, the report contains what you choose to include. The report form has consent toggles for attaching a screenshot and diagnostic logs; nothing is attached without those toggles.</p>

<h2>6. What we do not do</h2>
<ul>
<li>We do not sell your personal data.</li>
<li>We do not show ads or share your data with advertisers.</li>
<li>We do not use your care data for any purpose other than operating and improving the service.</li>
</ul>

<h2>7. Security</h2>
<p>Sync and AI traffic is encrypted in transit. Access to backend data is limited to what is needed to operate the service. No system is perfectly secure, so please use a device passcode and keep your sign-in credentials private.</p>

<h2>8. Data retention and deletion</h2>
<p>Synced data is retained while your account is active so your care circle keeps working. You can request deletion of your account and its server-side data at any time by emailing <a href="mailto:support@holdclose.care">support@holdclose.care</a>; deleting the app from your device removes the local database.</p>

<h2>9. Children's privacy</h2>
<p>Holdclose is intended for adult caregivers and is not directed at children under 13. We do not knowingly collect personal information from children under 13; if you believe a child has provided us personal information, contact us and we will delete it.</p>

<h2>10. Changes to this policy</h2>
<p>We may update this policy as the product evolves. If a change is material, we will give notice in the app or by email before it takes effect.</p>

<h2>11. Contact</h2>
<p>Juno Code Studio (JCSV One LLC) &middot; <a href="mailto:support@holdclose.care">support@holdclose.care</a></p>`,
);

/// Public legal pages (`GET /terms`, `GET /privacy`).
///
/// Mounted at the WORKER ROOT — like `/join`, deliberately OUTSIDE the
/// `/api/v1` sub-app and its JWT middleware — because they are plain web
/// pages the sign-in screen links to (https://holdclose.care/terms and
/// /privacy) before any account exists. Static HTML, no DB work.
export function termsRouter() {
  const router = new Hono<{ Bindings: Bindings; Variables: Variables }>();
  router.get('/', (c) => c.html(TERMS_HTML));
  return router;
}

export function privacyRouter() {
  const router = new Hono<{ Bindings: Bindings; Variables: Variables }>();
  router.get('/', (c) => c.html(PRIVACY_HTML));
  return router;
}
